### ISSUE TITLE
StaticInjectorError for TooltipService

### ISSUE THREAD

**Issue by zolee** [swimlane/ngx-graph#145]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Current version of ngx-graph throws error to the console and the graph won't render when --aot build used, therefore we cannot turn on aot nor build optimizer for production builds.

```ERROR Error: StaticInjectorError(AppModule)[TooltipService -> InjectionService]: 
  StaticInjectorError(Platform: core)[TooltipService -> InjectionService]: 
    NullInjectorError: No provider for InjectionService!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:3228)
    at resolveToken (core.js:3473)
    at tryResolveToken (core.js:3417)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:3314)
    at resolveToken (core.js:3473)
    at tryResolveToken (core.js:3417)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:3314)
    at resolveNgModuleDep (core.js:19784)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:20473)
    at resolveDep (core.js:20844)
```

It doesn't matter if I use tooltips or not in the graph the above mentioned error exists for both cases.

**Expected behavior**
The grap should be rendered correctly and the app should not throw any error.

**Reproduction of the problem**
Integrate ngx-graph in your app following the provided readme and try to ether run `ng serve --aot` or create a production angular build.

**Please tell us about your environment:**
npm 6.4.1, Angular CLI 7.1.3, webpack 4.26.0

* **ngx-graph version:** 5.1.1 but 5.2.1 also affected
* **Angular version:** 7.1.3
* **Browser:** all
* **Language:** all

**Comment by zolee** [comment]
#105

**Comment by zolee** [comment]
It seems the problem was caused by the import of `NgxChartsModule` in the `app.module.ts` file. The above mentioned error vanished after the removal of `NgxChartsModule` from `app.module.ts` file. You can close this issue. Thanks.

**Comment by jadielam** [comment]
I see that this issues are being closed, but I don't see a clear resolution stated anywhere on this thread. Can someone provide a solution to the problem?

**Comment by zolee** [comment]
Please check my previous comment: 
> the problem was caused by the import of NgxChartsModule in the app.module.ts

**Comment by nikolovski** [comment]
@jadielam Provide InjectionService in AppModule

```typescript 
@NgModule({
declarations: [...],
imports: [...],
providers: [InjectionService]

**Comment by kirtiesl** [comment]
Facing same problem.. anyone who got it working?

**Comment by nikolovski** [comment]
@kirtiesl see my comment above

**Comment by TestingAndDebugging** [comment]
In my case the problem only occurs in production... 
removing NgxChardModule doesnt help and providing InjectionService doesnt help neither

**Comment by denizkenan** [comment]
same issue when serving/building with --aot

**Comment by agusdutra** [comment]
@nikolovski I tried this and the problem persists. 
@zolee I can't remove this import because I'm using NgxCharts directly for other components.

**Comment by RolfVeinoeSorensen** [comment]
I have this issue as well with angular 8.0.2
ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[TooltipService -> InjectionService]: 
  StaticInjectorError(Platform: core)[TooltipService -> InjectionService]: 
    NullInjectorError: No provider for InjectionService!
NullInjectorError: StaticInjectorError(AppModule)[TooltipService -> InjectionService]: 
  StaticInjectorError(Platform: core)[TooltipService -> InjectionService]: 
    NullInjectorError: No provider for InjectionService!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:1225)
    at resolveToken (core.js:1463)
    at tryResolveToken (core.js:1407)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1311)
    at resolveToken (core.js:1463)
    at tryResolveToken (core.js:1407)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1311)
    at resolveNgModuleDep (core.js:18460)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:19149)
    at resolveNgModuleDep (core.js:18460)
    at resolvePromise (zone.js:852)
    at resolvePromise (zone.js:809)
    at zone.js:913
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:24340)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:502)
    at invokeTask (zone.js:1693)

**Comment by RolfVeinoeSorensen** [comment]
resolved in version 6.1.0

**Comment by kkseven07** [comment]
Still got this error when compiling in production. Any workarounds? Adding InjectionService to providers does not help

**Comment by agusdutra** [comment]
I could get it working with the latest update, also had to update angular to the latest version.

```
    "@angular/core": "^8.0.2",
    "@swimlane/ngx-charts": "^12.0.1",
    "@swimlane/ngx-graph": "6.1.0",
```

**Comment by kkseven07** [comment]
> I could get it working with the latest update, also had to update angular to the latest version.
> 
> ```
>     "@angular/core": "^8.0.2",
>     "@swimlane/ngx-charts": "^12.0.1",
>     "@swimlane/ngx-graph": "6.1.0",
> ```

didn't help with my `--configuration=ru`

**Comment by JoWood94** [comment]
Facing the same issue and tried all the solution linked before, 
`"@angular/core": "~8.2.14",
"@swimlane/ngx-charts": "12.0.1",
"@swimlane/ngx-graph": "^6.2.0",`
Does anyone have the solution?? adding or removing the modules (graph and chart) doesn't seem to solve nothing :/

**Comment by jesserogers** [comment]
My company's UI app is still running Angular 8 and we are having this problem. Tried updating to several newer versions of ngx-charts, but no luck, so I ended up just downloading the source at the version we we're using (`v10.0.0`) and adding `InjectionService` to the `providers` array for `ChartComponent` and it resolved my problem. Seems like a pretty easy fix?

**Comment by nomi-shah** [comment]
Facing the same error and tried all the solutions linked before,
"@angular/core": "~8.2.14", "@swimlane/ngx-charts": "12.0.1", "@swimlane/ngx-graph": "^6.1.0",
Does anyone have the solution??

**Comment by sweeneki** [comment]
Import ngx-charts in your package.json. KieranSent from my iPhone+41 79 959 37 59On Jan 17, 2023, at 18:28, nouman shah ***@***.***> wrote:﻿
Facing the same error and tried all the solutions linked before,
***@***.***/core": "~8.2.14", ***@***.***/ngx-charts": "12.0.1", ***@***.***/ngx-graph": "^6.1.0",
Does anyone have the solution??

**Comment by nomi-shah** [comment]
Already imported in package.json and in module.ts
