### ISSUE TITLE
TouchEvent is not defined error on module import

### ISSUE THREAD

**Issue by vincentfougeras** [swimlane/ngx-graph#99]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
When importing NgxGraphModule I get a ReferenceError in Firefox. There was no error when using ngx-graph 5.0.1.

**Reproduction of the problem**
```
import { NgxGraphModule } from '@swimlane/ngx-graph';

@NgModule({
  imports: [
    ...
    NgxGraphModule,
  ],
})
export class MyModule {}
```

![image](https://user-images.githubusercontent.com/12525740/41961341-8036a1d8-79f2-11e8-90e9-058bf4c8e2af.png)

**Please tell us about your environment:**

* **ngx-graph version:** 5.1.0

* **Angular version:** 6.0.6

* **Browser:** [ Firefox 60 ]

* **Language:** [ TypeScript 2.7.2 ]

**Comment by enigmatic** [comment]
It should be a simple fix https://stackoverflow.com/questions/27313488/touchevent-not-working-in-firefox-and-other-website-browser#32882849

**Comment by nicosaliagas** [comment]
I've got the same error.
Thanks in advance for the fix :)

**Comment by aniruddhadas9** [comment]
I am also getting the same issue. Any one have a workaround so solved this

**Comment by aniruddhadas9** [comment]
> Hi, so I have never contributed to any open source project and have never used GitHub, but I have locally fixed this issue by replacing the touch events with pointer events. But I can't figure out how to commit to this project, can anybody help?

@LoaderB0T fork the repo and they commit your code into your fork and they create a pull request so that owner and others can review it and finally merge it to the final one.

https://help.github.com/articles/working-with-forks/

**Comment by nicosaliagas** [comment]
@LoaderB0T did you achieved to make your pull request ?

**Comment by LoaderB0T** [comment]
@nicosaliagas Sorry to disappoint you, but we decided not to use the library due to mayor compatability issues with IE11. As mich as I would like to ditch it we have to support it for some of our customers.

**Comment by nicosaliagas** [comment]
@LoaderB0T did you use another similar lib ? I could be interested if so... :)

**Comment by LoaderB0T** [comment]
@nicosaliagas I used dagre without the design stuff and created my own svg graphics based on the calculated coordinates from dagrejs. (There are dts files for it)

**Comment by isaacplmann** [comment]
This issue is fixed in version 5.1.1

**Comment by assafsun** [comment]
Hi! when version 5.1.1 will be release? Can you please give more details on the fix?

**Comment by marjan-georgiev** [comment]
5.1.1 has been released for a while but the tag was not pushed to github. It is now. Also, 5.1.2 was released yesterday with updated dependencies. Closing this.

**Comment by sw2go** [comment]
the problem still remains, ReferenceError: TouchEvent is not defined see: https://github.com/sw2go/nodelink. Hack-Solution: remove:  @HostListener('document:touchmove', ['$event'])  in graph.component.ts
